version: '3.8'

services:
  app:
    build: .
    container_name: ss_gas_app
    restart: always
    env_file:
      - .env
    volumes:
      - ./frontend:/app/frontend
      - ./assets:/app/assets
      - ./test.db:/app/test.db  # BANCO DE DADOS AGORA É PERMANENTE!
    ports:
      - "8000:8000"
    networks:
      - gas-network

  caddy:
    image: caddy:latest
    container_name: ss_gas_ssl
    restart: always
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./Caddyfile:/etc/caddy/Caddyfile
      - caddy_data:/data
      - caddy_config:/config
    networks:
      - gas-network

networks:
  gas-network:
    driver: bridge

volumes:
  caddy_data:
  caddy_config:
